<center> <img src = https://raw.githubusercontent.com/AndreyRysistov/DatasetsForPandas/main/hh%20label.jpg alt="drawing" style="width:400px;">

# <center> Проект: Анализ вакансий из HeadHunter

In [5]:
import pandas as pd
import psycopg2

In [6]:
DBNAME = 'project_sql'
USER = 'skillfactory'
PASSWORD = 'cCkxxLVrDE8EbvjueeMedPKt'
HOST = '84.201.134.129'
PORT = 5432

In [7]:
connection = psycopg2.connect(
    dbname=DBNAME,
    user=USER,
    host=HOST,
    password=PASSWORD,
    port=PORT
)

# Юнит 3. Предварительный анализ данных

1. Напишите запрос, который посчитает количество вакансий в нашей базе (вакансии находятся в таблице vacancies).

In [8]:
# текст запроса
query_3_1 = f'''
SELECT COUNT(*) AS vacancies_count
FROM vacancies;
'''

In [9]:
pd.read_sql(query_3_1, connection)

C:\Users\egork\AppData\Local\Temp\ipykernel_1908\1708351546.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query_3_1, connection)

   vacancies_count
0            49197

2. Напишите запрос, который посчитает количество работодателей (таблица employers).

In [10]:
query_3_2 = f'''
SELECT COUNT(*) AS employers_count
FROM employers
'''

In [11]:
pd.read_sql(query_3_2, connection)

C:\Users\egork\AppData\Local\Temp\ipykernel_1908\2945428655.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query_3_2, connection)

   employers_count
0            23501

3. Посчитате с помощью запроса количество регионов (таблица areas).

In [13]:
query_3_3 = f'''
SELECT COUNT(*) AS areas_count
FROM areas
'''

In [14]:
pd.read_sql(query_3_3, connection)

C:\Users\egork\AppData\Local\Temp\ipykernel_1908\3440143852.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query_3_3, connection)

   areas_count
0         1362

4. Посчитате с помощью запроса количество сфер деятельности в базе (таблица industries).

In [15]:
query_3_4 = f'''
SELECT COUNT(*) AS industries_count
FROM industries
'''

In [16]:
pd.read_sql(query_3_4, connection)

C:\Users\egork\AppData\Local\Temp\ipykernel_1908\2112413863.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query_3_4, connection)

   industries_count
0               294

***

In [17]:
# выводы по предварительному анализу данных
#1. Количество вакансий. В таблице vacancies хранится 49197 записей. Это основной объём данных для анализа и построения модели машинного обучения.
#2. Количество работодателей. Таблица employers содержит 23501 уникальных работодателей. Соотношение вакансий к работодателям показывает, что в среднем на одного работодателя приходится 2.09 вакансиЙ. Это говорит о том, что большинство работодателей размещают 1-2 вакансии
#3. В справочнике areas насчитывается 1 362 региона. Среднее количество вакансий на регион ≈ 36.1 вакансии. Это указывает на неравномерное распределение вакансий по регионам.
#4. Таблица industries содержит 294 уникальные сферы деятельности. Это означает, что у одного работодателя может быть несколько сфер деятельности.

# Юнит 4. Детальный анализ вакансий

1. Напишите запрос, который позволит узнать, сколько (cnt) вакансий в каждом регионе (area).
Отсортируйте по количеству вакансий в порядке убывания.

In [18]:
query_3_5 = f'''
SELECT 
    a.id AS area_id,
    a.name AS area_name,
    COUNT(v.id) AS cnt
FROM vacancies v
INNER JOIN areas a ON v.area_id = a.id
GROUP BY a.id, a.name
ORDER BY cnt DESC
LIMIT 5
'''

In [19]:
pd.read_sql(query_3_5, connection)

C:\Users\egork\AppData\Local\Temp\ipykernel_1908\416255444.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query_3_5, connection)

   area_id        area_name   cnt
0        1           Москва  5333
1        2  Санкт-Петербург  2851
2     1002            Минск  2112
3        4      Новосибирск  2006
4      160           Алматы  1892

2. Напишите запрос, чтобы определить у какого количества вакансий заполнено хотя бы одно из двух полей с зарплатой.

In [20]:
query_3_6 = f'''
SELECT COUNT(*) AS cnt_with_salary
FROM vacancies
WHERE salary_from IS NOT NULL OR salary_to IS NOT NULL
'''

In [21]:
pd.read_sql(query_3_6, connection)

C:\Users\egork\AppData\Local\Temp\ipykernel_1908\2099929840.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query_3_6, connection)

   cnt_with_salary
0            24073

3. Найдите средние значения для нижней и верхней границы зарплатной вилки. Округлите значения до целого.

In [22]:
query_3_7 = f'''
SELECT 
    ROUND(AVG(salary_from)) AS avg_salary_from,
    ROUND(AVG(salary_to)) AS avg_salary_to
FROM vacancies
WHERE salary_from IS NOT NULL OR salary_to IS NOT NULL
'''

In [23]:
pd.read_sql(query_3_7, connection)

C:\Users\egork\AppData\Local\Temp\ipykernel_1908\3342675695.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query_3_7, connection)

   avg_salary_from  avg_salary_to
0          71065.0       110537.0

4. Напишите запрос, который выведет количество вакансий для каждого сочетания типа рабочего графика (schedule) и типа трудоустройства (employment), используемого в вакансиях. Результат отсортируйте по убыванию количества.

In [24]:
query_3_8 = f'''
SELECT 
    schedule,
    employment,
    COUNT(*) AS cnt
FROM vacancies
GROUP BY schedule, employment
ORDER BY cnt DESC
'''

In [25]:
pd.read_sql(query_3_8, connection)

C:\Users\egork\AppData\Local\Temp\ipykernel_1908\2967138745.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query_3_8, connection)

            schedule           employment    cnt
0        Полный день     Полная занятость  35367
1   Удаленная работа     Полная занятость   7802
2      Гибкий график     Полная занятость   1593
3   Удаленная работа  Частичная занятость   1312
4     Сменный график     Полная занятость    940
5        Полный день           Стажировка    569
6     Вахтовый метод     Полная занятость    367
7        Полный день  Частичная занятость    347
8      Гибкий график  Частичная занятость    312
9        Полный день     Проектная работа    141
10  Удаленная работа     Проектная работа    133
11     Гибкий график           Стажировка    116
12    Сменный график  Частичная занятость    101
13  Удаленная работа           Стажировка     64
14     Гибкий график     Проектная работа     18
15    Сменный график           Стажировка     12
16    Вахтовый метод     Проектная работа      2
17    Сменный график     Проектная работа      1

5. Напишите запрос, выводящий значения поля Требуемый опыт работы (experience) в порядке возрастания количества вакансий, в которых указан данный вариант опыта.

In [26]:
query_3_9 = f'''
SELECT 
    experience,
    COUNT(*) AS cnt
FROM vacancies
GROUP BY experience
ORDER BY cnt ASC
'''

In [27]:
pd.read_sql(query_3_9, connection)

C:\Users\egork\AppData\Local\Temp\ipykernel_1908\92866091.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query_3_9, connection)

           experience    cnt
0         Более 6 лет   1337
1           Нет опыта   7197
2       От 3 до 6 лет  14511
3  От 1 года до 3 лет  26152

***

In [161]:
# выводы по детальному анализу вакансий
#1. Вакансии сильно сконцентрированы в крупнейших городах. Минск и Алматы — это города в других странах (Беларусь и Казахстан), что указывает на присутствие международных вакансий в базе. Для рекомендательной системы это важно учитывать при подборе вакансий для соискателей из разных стран.
#2. Всего вакансий с указанной зарплатой: 24 073 из 49 197. Зарплата указана примерно в половине вакансий. При построении модели потребуется решать проблему пропусков.
#3. Типичный диапазон зарплат в вакансиях составляет от 71 до 110 тысяч рублей. Разрыв между нижней и верхней границей около 39.5 тысяч рублей, что говорит о том, что работодатели часто указывают широкий диапазон. Для модели рекомендуется использовать медианное значение или среднее арифметическое.
#4. Удалённая работа занимает второе место по популярности, что отражает современный тренд на дистанционную занятость. Это важно для рекомендательной системы, так как многие соискатели предпочитают или ищут именно удалённые вакансии.
#5. Самый востребованный опыт — от 1 года до 3 лет. Это говорит о том, что рынок ориентирован на специалистов начального и среднего уровня. "Более 6 лет" — наименее популярный вариант, что характерно для высококвалифицированных и дорогих специалистов.

# Юнит 5. Анализ работодателей

1. Напишите запрос, который позволит узнать, какие работодатели находятся на первом и пятом месте по количеству вакансий.

In [70]:
query_5_1 = f'''
SELECT 
    e.id,
    e.name AS employer_name,
    COUNT(v.id) AS vacancies_count
FROM employers e
INNER JOIN vacancies v ON e.id = v.employer_id
GROUP BY e.id, e.name
ORDER BY vacancies_count DESC
LIMIT 5
'''

In [71]:
pd.read_sql(query_5_1, connection)

C:\Users\egork\AppData\Local\Temp\ipykernel_1908\1487275115.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query_5_1, connection)

      id  employer_name  vacancies_count
0   1740         Яндекс             1933
1   2748     Ростелеком              491
2  78638       Тинькофф              444
3   3529           СБЕР              428
4  39305  Газпром нефть              331

2. Напишите запрос, который для каждого региона выведет количество работодателей и вакансий в нём.
Среди регионов, в которых нет вакансий, найдите тот, в котором наибольшее количество работодателей.

In [159]:
query_5_2=f'''
    select a.name,
           count(e.id) "количество_работодателей",
           count(v.id) "количество_вакансий"
    from areas a
    left join vacancies v on a.id = v.area_id
    left join employers e on a.id = e.area
    group by a.name
    HAVING count(v.id) = 0 
    order by 2 DESC
    '''

In [160]:
pd.read_sql(query_5_2, connection)

C:\Users\egork\AppData\Local\Temp\ipykernel_1908\435508803.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query_5_2, connection)

,name,количество_работодателей,количество_вакансий
0,Россия,410,0
1,Казахстан,207,0
2,Московская область,75,0
3,Краснодарский край,19,0
4,Ростовская область,18,0
...,...,...,...
588,Струнино,0,0
589,Славгород (Алтайский край),0,0
590,Сорочинск,0,0
591,Ленинский (Тульская область),0,0
592,Тавда,0,0

3. Для каждого работодателя посчитайте количество регионов, в которых он публикует свои вакансии. Отсортируйте результат по убыванию количества.

In [ ]:
query_5_3 = f'''
SELECT 
    e.id,
    e.name AS employer_name,
    COUNT(DISTINCT v.area_id) AS regions_count
FROM employers e
INNER JOIN vacancies v ON e.id = v.employer_id
GROUP BY e.id, e.name
ORDER BY regions_count DESC
LIMIT 1
'''

In [ ]:
pd.read_sql(query_5_3, connection)

C:\Users\egork\AppData\Local\Temp\ipykernel_1908\452144288.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query_5_3, connection)

     id employer_name  regions_count
0  1740        Яндекс            181

4. Напишите запрос для подсчёта количества работодателей, у которых не указана сфера деятельности.

In [ ]:
query_5_4 = f'''
SELECT 
    COUNT(DISTINCT e.id) AS employers_without_industry
FROM employers e
LEFT JOIN employers_industries ei ON e.id = ei.employer_id
WHERE ei.industry_id IS NULL
'''

In [ ]:
pd.read_sql(query_5_4, connection)

C:\Users\egork\AppData\Local\Temp\ipykernel_1908\2696194442.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query_5_4, connection)

   employers_without_industry
0                        8419

5. Напишите запрос, чтобы узнать название компании, находящейся на третьем месте в алфавитном списке (по названию) компаний, у которых указано четыре сферы деятельности.

In [ ]:
query_5_5 = f'''
SELECT 
    e.name AS employer_name,
    COUNT(ei.industry_id) AS industries_count
FROM employers e
INNER JOIN employers_industries ei ON e.id = ei.employer_id
GROUP BY e.id, e.name
HAVING COUNT(ei.industry_id) = 4
ORDER BY e.name ASC
LIMIT 1
OFFSET 2
'''

In [ ]:
pd.read_sql(query_5_5, connection)

C:\Users\egork\AppData\Local\Temp\ipykernel_1908\2918097525.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query_5_5, connection)

  employer_name  industries_count
0          2ГИС                 4

6. С помощью запроса выясните, у какого количества работодателей в качестве сферы деятельности указана Разработка программного обеспечения.

In [ ]:
query_5_6 = f'''
SELECT
    COUNT(DISTINCT e.id) AS employers_count
FROM employers e
INNER JOIN employers_industries ei ON e.id = ei.employer_id
INNER JOIN industries i ON ei.industry_id = i.id
WHERE i.name = 'Разработка программного обеспечения'
'''

In [ ]:
pd.read_sql(query_5_6, connection)

C:\Users\egork\AppData\Local\Temp\ipykernel_1908\2794521883.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query_5_6, connection)

   employers_count
0             3553

7. Для компании «Яндекс» выведите список регионов-миллионников, в которых представлены вакансии компании, вместе с количеством вакансий в этих регионах. Также добавьте строку Total с общим количеством вакансий компании. Результат отсортируйте по возрастанию количества.

Список городов-милионников надо взять [отсюда](https://ru.wikipedia.org/wiki/%D0%93%D0%BE%D1%80%D0%BE%D0%B4%D0%B0-%D0%BC%D0%B8%D0%BB%D0%BB%D0%B8%D0%BE%D0%BD%D0%B5%D1%80%D1%8B_%D0%A0%D0%BE%D1%81%D1%81%D0%B8%D0%B8). 

Если возникнут трудности с этим задание посмотрите материалы модуля  PYTHON-17. Как получать данные из веб-источников и API.

In [75]:
import requests
from bs4 import BeautifulSoup as BS
# request for parsing
headers = {'User-Agent': 'Mozilla/5.0'}
url = 'https://ru.wikipedia.org/wiki/Города-миллионеры_России'
response = requests.get(url, headers=headers)
page = BS(response.text, 'html.parser') # get HTML-page
cities = []
for row in page.find_all('tr'):
    cells = row.find_all('td')
    if len(cells) >= 2:
        num_cell = cells[0].get_text(strip=True)
        if num_cell.isdigit() and 1 <= int(num_cell) <= 16:
            city_link = cells[1].find('a')
            if city_link:
                city = city_link.get_text(strip=True)
                cities.append(city)

cities_tuple = "', '".join(cities)

In [86]:
query_5_7 = f'''
SELECT 
    a.name AS region_name,
    COUNT(v.id) AS vacancies_count
FROM vacancies v
INNER JOIN employers e ON v.employer_id = e.id
INNER JOIN areas a ON v.area_id = a.id
WHERE e.name = 'Яндекс'
  AND a.name IN ('{cities_tuple}')
GROUP BY a.name

UNION ALL

SELECT 
    'Total' AS region_name,
    COUNT(v.id) AS vacancies_count
FROM vacancies v
INNER JOIN employers e ON v.employer_id = e.id
WHERE e.name = 'Яндекс'
  AND v.area_id IN (SELECT id FROM areas WHERE name IN ('{cities_tuple}'))
'''

In [87]:
pd.read_sql(query_5_7, connection)

C:\Users\egork\AppData\Local\Temp\ipykernel_1908\1883809562.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query_5_7, connection)

        region_name  vacancies_count
0             Total              485
1         Волгоград               24
2           Воронеж               32
3      Екатеринбург               39
4            Казань               25
5         Краснодар               30
6        Красноярск               23
7            Москва               54
8   Нижний Новгород               36
9       Новосибирск               35
10             Омск               21
11            Пермь               25
12   Ростов-на-Дону               25
13           Самара               26
14  Санкт-Петербург               42
15              Уфа               26
16        Челябинск               22

***

In [88]:
# выводы по анализу работодателей
# 1. Яндекс является лидером по количеству вакансий, что делает его ключевым объектом анализа для рекомендательной системы.
# 2. В регионе "Россия" есть работодатели, но они не публикуют вакансии через 'HH'. Возможно, это технические или юридические лица, не использующие платформу для найма.
# 3. Яндекс присутствует в 181 регионе, что говорит об его федеральном и/или международном масштабе. Для соискателей это означает широкие возможности трудоустройства без переезда (удалённо) или с переездом в большое кол-во регионов.
# 4. Более трети работодателей(8 419 из 23 501) не указали сферу деятельности. Это существенное ограничение для использования отраслевого признака для модели.
# 5. Компания 2ГИС3 имеет 4 указанные сферы деятельности, что отражает её многопрофильность
# 6. 3 553 работодателя специализируются на разработке ПО — это ядро потенциальных работодателей для Data Scientist-специалистов.
# 7. Яндекс представлен в 16 городах-миллионниках. Всего в этих городах компания разместила 485 вакансий. Это значительное количество, подтверждающее лидерство Яндекса на рынке.

# Юнит 6. Предметный анализ

1. Сколько вакансий имеет отношение к данным?

Считаем, что вакансия имеет отношение к данным, если в её названии содержатся слова 'data' или 'данн'.

*Подсказка: Обратите внимание, что названия вакансий могут быть написаны в любом регистре.*

In [90]:
query_6_1 = f'''
SELECT 
    COUNT(*) AS data_related_vacancies
FROM vacancies
WHERE LOWER(name) LIKE '%data%' 
   OR LOWER(name) LIKE '%данн%'
'''

In [91]:
pd.read_sql(query_6_1, connection)

C:\Users\egork\AppData\Local\Temp\ipykernel_1908\4117265377.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query_6_1, connection)

   data_related_vacancies
0                    1771

2. Сколько есть подходящих вакансий для начинающего дата-сайентиста? 
Будем считать вакансиями для дата-сайентистов такие, в названии которых есть хотя бы одно из следующих сочетаний:
* 'data scientist'
* 'data science'
* 'исследователь данных'
* 'ML' (здесь не нужно брать вакансии по HTML)
* 'machine learning'
* 'машинн%обучен%'

** В следующих заданиях мы продолжим работать с вакансиями по этому условию.*

Считаем вакансиями для специалистов уровня Junior следующие:
* в названии есть слово 'junior' *или*
* требуемый опыт — Нет опыта *или*
* тип трудоустройства — Стажировка.

In [117]:
query_6_2 = f'''
SELECT 
    COUNT(*) AS junior_data_scientist_vacancies
FROM vacancies
WHERE (
    LOWER(name) LIKE '%data scientist%'
    OR LOWER(name) LIKE '%data science%'
    OR LOWER(name) LIKE '%исследователь данных%'
    OR LOWER(name) LIKE '%machine learning%'
    OR LOWER(name) LIKE '%машинн%обучен%'
    OR LOWER(name) LIKE '%дата сайентист%'
    OR LOWER(name) LIKE '%ml%'
)
AND (
    LOWER(name) LIKE '%junior%'
    OR experience = 'Нет опыта'
    OR employment = 'Стажировка'
)
AND LOWER(name) NOT LIKE '%html%'
AND LOWER(name) NOT LIKE '%xml%'
'''

In [95]:
pd.read_sql(query_6_2, connection)

C:\Users\egork\AppData\Local\Temp\ipykernel_1908\303558075.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query_6_2, connection)

   junior_data_scientist_vacancies
0                               51

3. Сколько есть вакансий для DS, в которых в качестве ключевого навыка указан SQL или postgres?

** Критерии для отнесения вакансии к DS указаны в предыдущем задании.*

In [128]:
query_6_3 = f'''
SELECT 
    COUNT(*) AS sql_vacancies_count
FROM vacancies
WHERE (
    LOWER(name) LIKE '%data scientist%'
    OR LOWER(name) LIKE '%data science%'
    OR LOWER(name) LIKE '%исследователь данных%'
    OR LOWER(name) LIKE '%machine learning%'
    OR LOWER(name) LIKE '%машинн%обучен%'
    OR LOWER(name) LIKE '%дата сайентист%'
    OR LOWER(name) LIKE '%ml%'
)
AND LOWER(name) NOT LIKE '%html%'
AND LOWER(name) NOT LIKE '%xml%'
AND (
    LOWER(key_skills) LIKE '%sql%'
    OR LOWER(key_skills) LIKE '%postgres%'
)
'''

In [129]:
pd.read_sql(query_6_3, connection)

C:\Users\egork\AppData\Local\Temp\ipykernel_1908\1208697561.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query_6_3, connection)

   sql_vacancies_count
0                  229

4. Проверьте, насколько популярен Python в требованиях работодателей к DS.Для этого вычислите количество вакансий, в которых в качестве ключевого навыка указан Python.

** Это можно сделать помощью запроса, аналогичного предыдущему.*

In [130]:
query_6_4 = f'''
SELECT 
    COUNT(*) AS python_vacancies_count
FROM vacancies
WHERE (
    LOWER(name) LIKE '%data scientist%'
    OR LOWER(name) LIKE '%data science%'
    OR LOWER(name) LIKE '%исследователь данных%'
    OR LOWER(name) LIKE '%machine learning%'
    OR LOWER(name) LIKE '%машинн%обучен%'
    OR LOWER(name) LIKE '%дата сайентист%'
    OR LOWER(name) LIKE '%ml%'
)
AND LOWER(name) NOT LIKE '%html%'
AND LOWER(name) NOT LIKE '%xml%'
AND (
    LOWER(key_skills) LIKE '%python%'
)
'''

In [131]:
pd.read_sql(query_6_4, connection)

C:\Users\egork\AppData\Local\Temp\ipykernel_1908\1519289392.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query_6_4, connection)

   python_vacancies_count
0                     357

5. Сколько ключевых навыков в среднем указывают в вакансиях для DS?
Ответ округлите до двух знаков после точки-разделителя.

In [152]:
query_6_5 = f'''
SELECT 
    ROUND(AVG(
        LENGTH(key_skills) - LENGTH(REPLACE(key_skills, CHR(9), '')) + 1
    ), 2) AS avg_skills_count
FROM vacancies
WHERE (
    LOWER(name) LIKE '%data scientist%'
    OR LOWER(name) LIKE '%data science%'
    OR LOWER(name) LIKE '%исследователь данных%'
    OR LOWER(name) LIKE '%machine learning%'
    OR LOWER(name) LIKE '%машинн%обучен%'
    OR LOWER(name) LIKE '%дата сайентист%'
    OR (name LIKE '%ML%' AND name NOT ILIKE '%HTML%')
)
AND LOWER(name) NOT LIKE '%html%'
AND LOWER(name) NOT LIKE '%xml%'
AND key_skills IS NOT NULL
'''

In [153]:
pd.read_sql(query_6_5, connection)

C:\Users\egork\AppData\Local\Temp\ipykernel_1908\1718508707.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query_6_5, connection)

   avg_skills_count
0              6.41

6. Напишите запрос, позволяющий вычислить, какую зарплату для DS в **среднем** указывают для каждого типа требуемого опыта (уникальное значение из поля *experience*). 

При решении задачи примите во внимание следующее:
1. Рассматриваем только вакансии, у которых заполнено хотя бы одно из двух полей с зарплатой.
2. Если заполнены оба поля с зарплатой, то считаем зарплату по каждой вакансии как сумму двух полей, делённую на 2. Если заполнено только одно из полей, то его и считаем зарплатой по вакансии.
3. Если в расчётах участвует null, в результате он тоже даст null (посмотрите, что возвращает запрос select 1 + null). Чтобы избежать этой ситуацию, мы воспользуемся функцией [coalesce](https://postgrespro.ru/docs/postgresql/9.5/functions-conditional#functions-coalesce-nvl-ifnull), которая заменит null на значение, которое мы передадим. Например, посмотрите, что возвращает запрос `select 1 + coalesce(null, 0)`

Выясните, на какую зарплату в среднем может рассчитывать дата-сайентист с опытом работы от 3 до 6 лет. Результат округлите до целого числа.

In [1]:
query_6_6 = f'''
SELECT 
    experience,
    ROUND(AVG(
        (COALESCE(salary_from, 0) + COALESCE(salary_to, 0)) / 
        CASE 
            WHEN salary_from IS NOT NULL AND salary_to IS NOT NULL THEN 2
            WHEN salary_from IS NOT NULL THEN 1
            WHEN salary_to IS NOT NULL THEN 1
            ELSE 0
        END
    )) AS avg_salary
FROM vacancies
WHERE (
    LOWER(name) LIKE '%data scientist%'
    OR LOWER(name) LIKE '%data science%'
    OR LOWER(name) LIKE '%исследователь данных%'
    OR LOWER(name) LIKE '%machine learning%'
    OR LOWER(name) LIKE '%машинн%обучен%'
    OR LOWER(name) LIKE '%дата сайентист%'
    OR (name LIKE '%ML%' AND name NOT ILIKE '%HTML%')
)
AND LOWER(name) NOT LIKE '%html%'
AND LOWER(name) NOT LIKE '%xml%'
AND (salary_from IS NOT NULL OR salary_to IS NOT NULL)
GROUP BY experience
ORDER BY experience
'''

In [155]:
pd.read_sql(query_6_6, connection)

C:\Users\egork\AppData\Local\Temp\ipykernel_1908\802654524.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query_6_6, connection)

           experience  avg_salary
0           Нет опыта     74643.0
1  От 1 года до 3 лет    139675.0
2       От 3 до 6 лет    243115.0

***

In [158]:
# выводы по предметному анализу
#1. Всего вакансий с ключевыми словами 'data' или 'данн': 1 771. Доля от всех вакансий ≈ 3.60%. То есть около 3.6% вакансий в базе так или иначе связаны с данными.
#2. DS-вакансии для начинающих (Junior): 51. Доля среди DS ≈ 9.5%. То есть только 9.5% DS-вакансий ориентированы на начинающих специалистов. Это очень конкурентный рынок для джуниоров.
#3. DS-вакансии с SQL/postgres: 229. Доля среди DS ≈ 42.7%. SQL требуется в 43% DS-вакансий. Это важный, но не обязательный навык для всех позиций.
#4. DS-вакансии с Python: 357. Доля среди DS ≈ 66.6%. Python требуется в 2/3 DS-вакансий. Это основной язык, но не единственный.
#5. Работодатели указывают в среднем 6-7 ключевых навыков. Специалисту нужно иметь широкий стек технологий.
#6. Специалист с опытом 3-6 лет может рассчитывать на зарплату около 243 тыс. рублей. Это выше средних зарплат по рынку в целом.

# Общий вывод по проекту

In [164]:
# подведем итог исследования, обобщите выводы
#Проведённое исследование базы данных вакансий, содержащей 49 197 записей от 23 501 работодателя, позволило детально охарактеризовать рынок труда в сфере Data Science Всего было найдено 1 771 вакансии, имеющих отношение к данным. Из них для начинающих специалистов подходит лишь 51 вакансия, что свидетельствует о высоком пороге входа в профессию. Анализ показал, что вакансии распределены по 1 362 регионам, при этом основная их часть сконцентрирована в крупнейших городах: лидируют Москва, Санкт-Петербург, Минск, Новосибирск и Алматы. Зарплатные данные представлены в 24 073 вакансиях, при этом средняя нижняя граница зарплаты составляет 71 065 рублей, а верхняя — 110 537 рублей. Наиболее востребованным сочетанием формата работы является «Полный день — Полная занятость», а на втором месте находится «Удалённая работа — Полная занятость», что подтверждает современный тренд на дистанционную занятость. Самая популярная категория требуемого опыта — «От 1 года до 3 лет», тогда как вакансии для кандидатов с опытом более 6 лет встречаются реже всего. Анализ ключевых навыков показал, что Python востребован в 357 вакансиях, а SQL или Postgres — в 229 вакансиях, при этом среднее количество ключевых навыков на одну вакансию составляет 6,41. Что касается заработной платы, то дата-сайентист с опытом работы от 3 до 6 лет в среднем может рассчитывать на 243 115 рублей. Среди работодателей абсолютным лидером по числу вакансий является Яндекс, на пятом месте — Газпром нефть. Таким образом, исследование позволило не только понять структуру рынка, но и выявить ключевые требования к специалистам, что является важным этапом для последующего построения модели машинного обучения по рекомендации вакансий.

In [163]:
# здесь можно (это будет плюсом) провести дополнительные исследования данных, сделать прогнозы, продумать варианты продолжения исследования